# Generated by Django 2.2.6 on 2019-11-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Telefone'), ('2', 'Celular'), ('3', 'Email')], default='1', max_length=3)),
                ('contato', models.CharField(blank=True, help_text='informe o contato', max_length=255, null=True, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('contato', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NovoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.TextField(blank=True, max_length=255, null=True)),
                ('fantasia', models.TextField(blank=True, max_length=255, null=True)),
                ('fone1', models.TextField(blank=True, max_length=255, null=True)),
                ('fone2', models.TextField(blank=True, max_length=255, null=True)),
                ('celular', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('cnpj', models.TextField(blank=True, max_length=255, null=True)),
                ('ie', models.TextField(blank=True, max_length=255, null=True)),
                ('sla', models.CharField(choices=[('2', '1'), ('3', '2'), ('4', '3')], default='1', max_length=1)),
                ('ativo', models.CharField(choices=[('1', 'Nao'), ('2', 'Sim')], default='Nao', max_length=1)),
                ('Financeiro', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Em andamento'), ('2', 'Finalizado'), ('3', 'Suspenso'), ('4', 'Cancelado')], default='1', max_length=1)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('paga_almoco', models.CharField(choices=[('1', 'Nao'), ('2', 'Sim')], default='1', max_length=1)),
                ('paga_translado', models.CharField(choices=[('1', 'Nao'), ('2', 'Sim')], default='1', max_length=1)),
                ('tempo_viagem', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_hora', models.CharField(blank=True, max_length=255, null=True)),
                ('anexo', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('localDeAtendimento', models.TextField(blank=True, null=True)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('desconto', models.CharField(blank=True, max_length=255, null=True)),
                ('contato', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('analista', models.CharField(blank=True, max_length=255, null=True)),
                ('data_atendimento', models.CharField(blank=True, max_length=255, null=True)),
                ('chamado', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('1', 'Em andamento'), ('2', 'Finalizado'), ('3', 'Suspenso'), ('4', 'Cancelado'), ('5', '')], default='5', max_length=1)),
                ('descritivos', models.CharField(blank=True, max_length=255, null=True)),
                ('anexo', models.ImageField(upload_to='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.NovoCliente')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaFilial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa_matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.EmpresaMatriz')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Informe seu nome', max_length=255, verbose_name='Nome')),
                ('last_name', models.CharField(help_text='Informe seu sobrenome', max_length=255, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, help_text='Informe o numero de celular', max_length=255, null=True, verbose_name='telefone')),
                ('celular', models.CharField(blank=True, help_text='Informe o número do celular', max_length=255, null=True, verbose_name='Celular')),
                ('equipe', models.CharField(choices=[('1', '5GO'), ('2', 'Connit'), ('3', 'Infra'), ('4', 'Prima Info'), ('5', 'Sistemas')], default='5', max_length=1)),
                ('cpf', models.CharField(blank=True, help_text='Informe seu CPF', max_length=255, null=True, verbose_name='CPF')),
                ('nivel', models.CharField(choices=[('1', 'Administrador'), ('2', 'Analista'), ('3', 'Tercerizado'), ('4', 'Cliente'), ('5', 'Coordenador'), ('6', 'Ex-funcionario')], default='4', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Desativado')], default='2', max_length=1)),
                ('reset_pass', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('consultoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Consultoria')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
