# Generated by Django 2.2.6 on 2019-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, max_length=255, null=True)),
                ('telefone', models.TextField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Desativado')], default='1', max_length=1),
        ),
    ]
