# Generated by Django 2.2.6 on 2019-11-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191113_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.TextField(blank=True, max_length=255, null=True)),
                ('setor', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_atendimento',
            field=models.CharField(choices=[('1', ''), ('2', 'Presencial'), ('3', 'Remoto'), ('4', 'Projeto')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_fechado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Concluido'), ('3', 'Desativado')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Concluido'), ('3', 'Desativado')], default='1', max_length=1),
        ),
    ]
