# Generated by Django 2.2.6 on 2019-11-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191113_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novocliente',
            name='Financeiro',
        ),
        migrations.RemoveField(
            model_name='novocliente',
            name='sla',
        ),
    ]
