# Generated by Django 2.2.6 on 2019-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191114_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='localDeAtendimento',
            new_name='responsavel',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='chamado',
            new_name='translado',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_atendimento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='telefone',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='dataAtendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipoDeAtendimento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
