# Generated by Django 2.2.6 on 2019-11-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191126_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.NovoCliente'),
        ),
    ]
