# Generated by Django 2.2.6 on 2019-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191128_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
