# Generated by Django 2.2.6 on 2019-11-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191128_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='descritivos',
            new_name='descritivo',
        ),
    ]
